# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wlin <wlin@student.42barcelona.>           +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/09 20:06:48 by wlin              #+#    #+#              #
#    Updated: 2023/09/09 20:06:54 by wlin             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

FLAGS = -Wall -Werror -Wextra

SRC = ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c ft_isprint \
ft_strlen.c ft_tolower.c ft_toupper.c

BSRC =

HEADER = libft.h

OBJ =

OBJBONUS =

all:

...

$(NAME): $(OBJ)
		ar rc $(NAME) $(OBJ)

bonus:

.bonus:

clean:
	rm -f$(OBJ)$(OBJBONUS).bonus

fclean: clean
	rm -f $(NAME)
	re:fclean all

.PHONY:
